"""agnes — type-hinted database toolkit with a Rust core and a self-invalidating cache.

Python port of agnes-library (TypeScript). Same schema DSL, query builder,
relations and cache; synchronous API.
"""

from .client import AgnesClient, TransactionClient
from .ddl import create_table_sql, generate_schema_ddl
from .query import (
    DeleteBuilder,
    InsertBuilder,
    SelectBuilder,
    SelectStart,
    UpdateBuilder,
    and_,
    avg,
    between,
    count,
    eq,
    gt,
    gte,
    ilike,
    in_array,
    is_not_null,
    is_null,
    like,
    lt,
    lte,
    max_,
    min_,
    neq,
    not_,
    not_in_array,
    on,
    or_,
    query,
    render_condition,
    sum_,
)
from .schema import (
    Column,
    ManyRelation,
    OnAction,
    OneRelation,
    TableEntry,
    bigint,
    bool_,
    bytes_,
    flatten_schema,
    float_,
    int_,
    json_,
    many,
    one,
    table,
    text,
)

__all__ = [
    "AgnesClient",
    "TransactionClient",
    "table",
    "int_",
    "bigint",
    "text",
    "bool_",
    "float_",
    "bytes_",
    "json_",
    "one",
    "many",
    "OnAction",
    "Column",
    "TableEntry",
    "OneRelation",
    "ManyRelation",
    "flatten_schema",
    "eq",
    "neq",
    "gt",
    "gte",
    "lt",
    "lte",
    "like",
    "ilike",
    "in_array",
    "not_in_array",
    "is_null",
    "is_not_null",
    "between",
    "and_",
    "or_",
    "not_",
    "render_condition",
    "count",
    "sum_",
    "avg",
    "min_",
    "max_",
    "query",
    "on",
    "SelectBuilder",
    "SelectStart",
    "InsertBuilder",
    "UpdateBuilder",
    "DeleteBuilder",
    "generate_schema_ddl",
    "create_table_sql",
]
