-- Migration 20260701102435_auto.sql
-- Generated by `agnes migrate`

CREATE TABLE "users" (
  "id" integer PRIMARY KEY,
  "name" text NOT NULL,
  "email" text NOT NULL,
  "age" integer NOT NULL,
  "active" integer NOT NULL DEFAULT 1
);

CREATE INDEX "users_name_idx" ON "users" ("name");

CREATE UNIQUE INDEX "users_email_idx" ON "users" ("email");

CREATE TABLE "posts" (
  "id" integer PRIMARY KEY,
  "user_id" integer NOT NULL,
  "title" text NOT NULL,
  "body" text NOT NULL,
  CONSTRAINT "fk_posts_user_id" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE CASCADE
);
