import { resolve } from "node:path";
import type { Dialect } from "./dialect";
import type { DslSchema } from "./ir";

export interface CacheConfig {
  enabled: boolean;
  walPath?: string;
  compactionThreshold?: number;
}

export interface AgnesConfig {
  /** Target database dialect. */
  driver: Dialect;
  /** Connection URL, e.g. postgres://user:pass@host/db or sqlite://./dev.db */
  url: string;
  /** The schema object exported from your schema.ts (`export const schema = {...}`). */
  schema: DslSchema;
  /** Where `pull` writes the generated schema (default: ./schema.ts).
   * In `multifile` mode this is treated as a directory (default: ./schema). */
  out?: string;
  /**
   * PostgreSQL schemas to introspect on `pull`/`push` (default: `["public"]`).
   * Tables outside the default schema get qualified physical names ("auth.users").
   */
  schemas?: string[];
  /**
   * How `pull` lays out the generated schema:
   *  - "singlefile" (default): every table in one file.
   *  - "multifile": one file per DB schema + an index re-exporting them merged.
   */
  pullMode?: "singlefile" | "multifile";
  /**
   * Target language emitted by `pull` (schema files) and `generate` (client):
   *  - "ts" (default) → TypeScript, `agnes-library`
   *  - "py"           → Python, the `agnes` package
   * `generate` also infers "py" from a `.py` output path. Note: `push`/`migrate`
   * still read the TypeScript `schema` from this config.
   */
  lang?: "ts" | "py";
  /** Directory for versioned migration files (default: ./migrations). */
  migrationsDir?: string;
  maxConnections?: number;
  /**
   * Return temporal values without a timezone offset (naive wall-clock ISO) —
   * avoids the JS `Date` tz-shift footgun. Postgres only; defaults to false.
   */
  stripTimezone?: boolean;
  /** Cache config baked into the client generated by `agnes generate`. */
  cache?: CacheConfig;
  /**
   * Output path for `agnes generate` — the pre-wired AgnesClient module.
   * Extension decides the language: `.ts` or `.js`. Nested dirs are created.
   * e.g. "src/services/db.ts" or "db.js".
   */
  output?: string;
  /**
   * Env var holding the connection URL. When set, `agnes generate` emits
   * `process.env[urlEnv]` in the client instead of inlining the literal URL —
   * so credentials stay in your .env and never land in the generated file.
   */
  urlEnv?: string;
  /**
   * Module that exports `schema`, imported by the generated client.
   * Default: `out` (the pull target) or "./schema". A filesystem path
   * (e.g. "./schema.ts") — the generated import is made relative automatically.
   */
  schemaPath?: string;
}

/** Identity helper for type-checked config files. */
export function defineConfig(config: AgnesConfig): AgnesConfig {
  return config;
}

const CANDIDATES = ["agnes.config.ts", "agnes.config.js", "agnes.config.mjs"];

/** Load and validate the config file (explicit path or auto-discovered). */
export async function loadConfig(explicitPath?: string): Promise<AgnesConfig> {
  let path: string | undefined;
  if (explicitPath) {
    path = resolve(process.cwd(), explicitPath);
  } else {
    for (const c of CANDIDATES) {
      const p = resolve(process.cwd(), c);
      if (await Bun.file(p).exists()) {
        path = p;
        break;
      }
    }
  }
  if (!path) {
    throw new Error(
      `No config found. Create agnes.config.ts (see agnes-cli README) or pass --config <path>.`,
    );
  }

  const mod = (await import(path)) as { default?: AgnesConfig } & Partial<AgnesConfig>;
  const config = mod.default ?? (mod as AgnesConfig);

  if (!config?.driver || !config.url || !config.schema) {
    throw new Error(`Config at ${path} must export { driver, url, schema }.`);
  }
  return config;
}
