import type { ColumnType, DatabaseIR, TableIR } from "./ir";

const HELPER: Record<ColumnType, string> = {
  int: "int",
  bigint: "bigint",
  text: "text",
  bool: "bool",
  float: "float",
  bytes: "bytes",
  json: "json",
};

const ON_ACTION: Record<string, string> = {
  "NO ACTION": "OnAction.None",
  RESTRICT: "OnAction.Restrict",
  CASCADE: "OnAction.Cascade",
  "SET NULL": "OnAction.SetNull",
  "SET DEFAULT": "OnAction.SetDefault",
};

function onAction(rule: string): string {
  return ON_ACTION[rule.toUpperCase()] ?? "OnAction.None";
}

function literal(v: unknown): string {
  if (typeof v === "boolean") return String(v);
  if (typeof v === "number" || typeof v === "bigint") return String(v);
  return JSON.stringify(String(v));
}

function tableSource(t: TableIR): string {
  const fkByColumn = new Map(t.foreignKeys.map((fk) => [fk.column, fk]));
  const lines: string[] = [];

  for (const col of t.columns) {
    let expr = `${HELPER[col.type]}(${JSON.stringify(col.name)})`;
    if (col.primary) expr += ".primary()";
    else if (col.nullable) expr += ".nullable()";
    if (col.default !== undefined) expr += `.default(${literal(col.default)})`;
    for (const idx of t.indexes) {
      if (idx.columns.length === 1 && idx.columns[0] === col.name) {
        expr += idx.unique
          ? `.uniqueIndex(${JSON.stringify(idx.name)})`
          : `.index(${JSON.stringify(idx.name)})`;
      }
    }
    lines.push(`    ${col.name}: ${expr},`);
  }

  for (const fk of fkByColumn.values()) {
    // Relation TS key: derive from referenced table (best effort).
    const relKey = fk.refTable;
    lines.push(
      `    ${relKey}: one(${JSON.stringify(fk.refTable)}, ${JSON.stringify(fk.column)}, ` +
        `${JSON.stringify(fk.refColumn)}, ${onAction(fk.onUpdate)}, ${onAction(fk.onDelete)}),`,
    );
  }

  return `  ${t.name}: table({\n${lines.join("\n")}\n  }, ${JSON.stringify(t.name)}),`;
}

/** Render a full DatabaseIR into schema.ts source code. */
export function printSchema(ir: DatabaseIR): string {
  const tables = Object.values(ir)
    .sort((a, b) => a.name.localeCompare(b.name))
    .map(tableSource)
    .join("\n");

  return (
    `// Generated by \`agnes pull\`. Edit and re-run \`agnes push\` to apply changes.\n` +
    `import { table, int, bigint, text, bool, float, bytes, json, one, OnAction } from "agnes-library";\n\n` +
    `export const schema = {\n${tables}\n};\n`
  );
}
