import { qualifiedName, type ColumnType, type DatabaseIR, type TableIR } from "./ir";

const HELPER: Record<ColumnType, string> = {
  int: "int",
  bigint: "bigint",
  text: "text",
  bool: "bool",
  float: "float",
  bytes: "bytes",
  json: "json",
};

const ON_ACTION: Record<string, string> = {
  "NO ACTION": "OnAction.None",
  RESTRICT: "OnAction.Restrict",
  CASCADE: "OnAction.Cascade",
  "SET NULL": "OnAction.SetNull",
  "SET DEFAULT": "OnAction.SetDefault",
};

const HEADER =
  `import { table, int, bigint, text, bool, float, bytes, json, one, OnAction } from "agnes-library";\n`;

function onAction(rule: string): string {
  return ON_ACTION[rule.toUpperCase()] ?? "OnAction.None";
}

function literal(v: unknown): string {
  if (typeof v === "boolean") return String(v);
  if (typeof v === "number" || typeof v === "bigint") return String(v);
  return JSON.stringify(String(v));
}

/** A qualified name → a valid JS identifier (for the `schema` object keys / relation keys). */
function idKey(name: string): string {
  return name.replace(/[^A-Za-z0-9_]/g, "_");
}

function tableSource(t: TableIR): string {
  const physical = qualifiedName(t.name, t.schema);
  const fkByColumn = new Map(t.foreignKeys.map((fk) => [fk.column, fk]));
  const lines: string[] = [];

  for (const col of t.columns) {
    let expr = `${HELPER[col.type]}(${JSON.stringify(col.name)})`;
    if (col.primary) expr += ".primary()";
    else if (col.nullable) expr += ".nullable()";
    if (col.default !== undefined) expr += `.default(${literal(col.default)})`;
    for (const idx of t.indexes) {
      if (idx.columns.length === 1 && idx.columns[0] === col.name) {
        expr += idx.unique
          ? `.uniqueIndex(${JSON.stringify(idx.name)})`
          : `.index(${JSON.stringify(idx.name)})`;
      }
    }
    lines.push(`    ${col.name}: ${expr},`);
  }

  for (const fk of fkByColumn.values()) {
    // Relation TS key: derive from referenced table (best effort).
    const relKey = idKey(fk.refTable);
    lines.push(
      `    ${relKey}: one(${JSON.stringify(fk.refTable)}, ${JSON.stringify(fk.column)}, ` +
        `${JSON.stringify(fk.refColumn)}, ${onAction(fk.onUpdate)}, ${onAction(fk.onDelete)}),`,
    );
  }

  return `  ${idKey(physical)}: table({\n${lines.join("\n")}\n  }, ${JSON.stringify(physical)}),`;
}

function schemaBlock(tables: TableIR[]): string {
  const body = tables
    .slice()
    .sort((a, b) => qualifiedName(a.name, a.schema).localeCompare(qualifiedName(b.name, b.schema)))
    .map(tableSource)
    .join("\n");
  return `export const schema = {\n${body}\n};\n`;
}

/** Render a full DatabaseIR into a single schema.ts source string. */
export function printSchema(ir: DatabaseIR): string {
  return (
    `// Generated by \`agnes pull\`. Edit and re-run \`agnes push\` to apply changes.\n` +
    HEADER +
    `\n` +
    schemaBlock(Object.values(ir))
  );
}

export interface SchemaFile {
  /** Bare file name without extension, e.g. "public", "auth". */
  name: string;
  source: string;
}

/**
 * Render a DatabaseIR into one file per DB schema plus an `index` that
 * re-exports every file's tables merged into a single `schema` object.
 */
export function printSchemaFiles(ir: DatabaseIR): { files: SchemaFile[]; index: string } {
  const bySchema = new Map<string, TableIR[]>();
  for (const t of Object.values(ir)) {
    const key = t.schema ?? "public";
    (bySchema.get(key) ?? bySchema.set(key, []).get(key)!).push(t);
  }

  const names = [...bySchema.keys()].sort();
  const files: SchemaFile[] = names.map((name) => ({
    name,
    source:
      `// Generated by \`agnes pull\`. Schema "${name}".\n` +
      HEADER +
      `\n` +
      schemaBlock(bySchema.get(name)!),
  }));

  // Alias with a "Schema" suffix so reserved words (e.g. "public") stay valid bindings.
  const alias = (n: string) => `${idKey(n)}Schema`;
  const imports = names
    .map((n) => `import { schema as ${alias(n)} } from ${JSON.stringify(`./${n}`)};`)
    .join("\n");
  const spread = names.map((n) => `  ...${alias(n)},`).join("\n");
  const index =
    `// Generated by \`agnes pull\`. Merges every per-schema file into one \`schema\`.\n` +
    `${imports}\n\nexport const schema = {\n${spread}\n};\n`;

  return { files, index };
}
