import { qualifiedName, type ColumnType, type DatabaseIR, type TableIR } from "./ir";

// Python DSL printer — mirrors print.ts but emits `agnes` (Python) source.

const HELPER: Record<ColumnType, string> = {
  int: "int_",
  bigint: "bigint",
  text: "text",
  bool: "bool_",
  float: "float_",
  bytes: "bytes_",
  json: "json_",
};

const ON_ACTION: Record<string, string> = {
  "NO ACTION": "OnAction.NONE",
  RESTRICT: "OnAction.RESTRICT",
  CASCADE: "OnAction.CASCADE",
  "SET NULL": "OnAction.SET_NULL",
  "SET DEFAULT": "OnAction.SET_DEFAULT",
};

const HEADER =
  `from agnes import table, int_, bigint, text, bool_, float_, bytes_, json_, one, OnAction\n`;

function onAction(rule: string): string {
  return ON_ACTION[rule.toUpperCase()] ?? "OnAction.NONE";
}

function idKey(name: string): string {
  return name.replace(/[^A-Za-z0-9_]/g, "_");
}

/** Render a raw DB default into the `.default(...)` argument, or null to omit. */
function renderDefault(type: ColumnType, raw: unknown): string | null {
  if (raw === undefined || raw === null) return null;
  const s = String(raw).trim();
  const cast = s.replace(/::[\w\s"]+$/, "").trim();
  const quoted = cast.match(/^'([\s\S]*)'$/);
  const inner = quoted ? quoted[1]!.replace(/''/g, "'") : undefined;
  const scalar = inner ?? cast;

  switch (type) {
    case "bool": {
      const t = scalar.toLowerCase();
      if (t === "true" || t === "t" || t === "1") return "True";
      if (t === "false" || t === "f" || t === "0") return "False";
      return null;
    }
    case "int":
    case "bigint":
    case "float": {
      const n = Number(scalar);
      return scalar !== "" && Number.isFinite(n) ? String(n) : null;
    }
    case "text":
    case "json":
      return inner !== undefined ? JSON.stringify(inner) : null;
    default:
      return null;
  }
}

/** Render `table({...}, "physical")`. `pad` indents the column lines. */
function tableBody(t: TableIR, pad: string): string {
  const physical = qualifiedName(t.name, t.schema);
  const fkByColumn = new Map(t.foreignKeys.map((fk) => [fk.column, fk]));
  const lines: string[] = [];

  const usedKeys = new Set(t.columns.map((col) => col.name));
  const relKeyFor = (fk: { column: string; refTable: string }): string => {
    const base = idKey(fk.column.replace(/_?id$/i, "")) || idKey(fk.refTable);
    let key = base;
    for (let n = 2; usedKeys.has(key); n++) key = `${base}_${n}`;
    usedKeys.add(key);
    return key;
  };

  for (const col of t.columns) {
    let expr = `${HELPER[col.type]}(${JSON.stringify(col.name)})`;
    if (col.primary) expr += ".primary()";
    else if (col.nullable) expr += ".nullable()";
    if (col.autoincrement) {
      expr += ".autoincrement()";
    } else {
      const d = renderDefault(col.type, col.default);
      if (d !== null) expr += `.default(${d})`;
    }
    for (const idx of t.indexes) {
      if (idx.columns.length === 1 && idx.columns[0] === col.name) {
        expr += idx.unique
          ? `.unique_index(${JSON.stringify(idx.name)})`
          : `.index(${JSON.stringify(idx.name)})`;
      }
    }
    lines.push(`${pad}    ${JSON.stringify(col.name)}: ${expr},`);
  }

  for (const fk of fkByColumn.values()) {
    const relKey = relKeyFor(fk);
    lines.push(
      `${pad}    ${JSON.stringify(relKey)}: one(${JSON.stringify(fk.refTable)}, ` +
        `${JSON.stringify(fk.column)}, ${JSON.stringify(fk.refColumn)}, ` +
        `${onAction(fk.onUpdate)}, ${onAction(fk.onDelete)}),`,
    );
  }

  return `table({\n${lines.join("\n")}\n${pad}}, ${JSON.stringify(physical)})`;
}

const byQualified = (a: TableIR, b: TableIR) =>
  qualifiedName(a.name, a.schema).localeCompare(qualifiedName(b.name, b.schema));

/** Render the `schema = { ... }` dict. Non-public tables are grouped by schema. */
function schemaObject(tables: TableIR[]): string {
  const top: TableIR[] = [];
  const groups = new Map<string, TableIR[]>();
  for (const t of tables) {
    if (!t.schema || t.schema === "public") top.push(t);
    else (groups.get(t.schema) ?? groups.set(t.schema, []).get(t.schema)!).push(t);
  }

  const lines: string[] = [];
  for (const t of top.sort(byQualified)) {
    lines.push(`    ${JSON.stringify(t.name)}: ${tableBody(t, "    ")},`);
  }
  for (const schema of [...groups.keys()].sort()) {
    const inner = groups
      .get(schema)!
      .sort(byQualified)
      .map((t) => `        ${JSON.stringify(t.name)}: ${tableBody(t, "        ")},`)
      .join("\n");
    lines.push(`    ${JSON.stringify(schema)}: {\n${inner}\n    },`);
  }
  return `schema = {\n${lines.join("\n")}\n}\n`;
}

/** Render a full DatabaseIR into a single schema.py source string. */
export function printSchemaPy(ir: DatabaseIR): string {
  return (
    `# Generated by \`agnes pull\`. Edit and re-run \`agnes push\` to apply changes.\n` +
    HEADER +
    `\n` +
    schemaObject(Object.values(ir))
  );
}

export interface SchemaFilePy {
  name: string;
  source: string;
}

/**
 * Render into one file per DB schema plus `__init__.py` merging them into one
 * `schema` dict — the output directory becomes an importable package.
 */
export function printSchemaFilesPy(ir: DatabaseIR): { files: SchemaFilePy[]; index: string } {
  const bySchema = new Map<string, TableIR[]>();
  for (const t of Object.values(ir)) {
    const key = t.schema ?? "public";
    (bySchema.get(key) ?? bySchema.set(key, []).get(key)!).push(t);
  }

  const names = [...bySchema.keys()].sort();
  const files: SchemaFilePy[] = names.map((name) => ({
    name,
    source:
      `# Generated by \`agnes pull\`. Schema "${name}".\n` + HEADER + `\n` + schemaObject(bySchema.get(name)!),
  }));

  const alias = (n: string) => `${idKey(n)}_schema`;
  const imports = names.map((n) => `from .${n} import schema as ${alias(n)}`).join("\n");
  const merged = names.map((n) => `**${alias(n)}`).join(", ");
  const index =
    `# Generated by \`agnes pull\`. Merges every per-schema module into one \`schema\`.\n` +
    `${imports}\n\nschema = {${merged}}\n`;

  return { files, index };
}
