import { dirname, relative, resolve } from "node:path";
import type { AgnesConfig } from "../config";
import { c } from "../prompt";

export interface GenerateArgs {
  output?: string;
  yes?: boolean;
}

/** Turn a filesystem path into a relative ESM import specifier (no extension). */
function toImportSpecifier(fromFile: string, toModule: string): string {
  let rel = relative(dirname(fromFile), toModule).replace(/\\/g, "/");
  rel = rel.replace(/\.(ts|tsx|js|jsx|mjs|cjs)$/, "");
  if (!rel.startsWith(".")) rel = `./${rel}`;
  return rel;
}

function renderUrl(config: AgnesConfig): string {
  // Never inline credentials: when urlEnv is set, read the URL from the
  // environment at runtime so the generated file stays secret-free.
  if (config.urlEnv) return `process.env[${JSON.stringify(config.urlEnv)}]!`;
  return JSON.stringify(config.url);
}

function renderConfigObject(config: AgnesConfig): string {
  const lines: string[] = [
    `    driver: ${JSON.stringify(config.driver)},`,
    `    url: ${renderUrl(config)},`,
  ];
  if (config.maxConnections !== undefined)
    lines.push(`    maxConnections: ${config.maxConnections},`);
  if (config.stripTimezone !== undefined)
    lines.push(`    stripTimezone: ${config.stripTimezone},`);
  if (config.cache) {
    const parts = [`enabled: ${config.cache.enabled}`];
    if (config.cache.walPath !== undefined) parts.push(`walPath: ${JSON.stringify(config.cache.walPath)}`);
    if (config.cache.compactionThreshold !== undefined)
      parts.push(`compactionThreshold: ${config.cache.compactionThreshold}`);
    lines.push(`    cache: { ${parts.join(", ")} },`);
  }
  return lines.join("\n");
}

function renderClient(config: AgnesConfig, schemaImport: string): string {
  return (
    `// Generated by \`agnes generate\`. Do not edit — re-run to regenerate.\n` +
    `import { AgnesClient } from "agnes-library";\n` +
    `import { schema } from ${JSON.stringify(schemaImport)};\n\n` +
    `export const db = await AgnesClient.create(\n` +
    `  {\n${renderConfigObject(config)}\n  },\n` +
    `  schema,\n` +
    `);\n`
  );
}

// ── Python target ────────────────────────────────────────────────────────────

function pyBool(v: boolean): string {
  return v ? "True" : "False";
}

function renderConfigObjectPy(config: AgnesConfig): string {
  const url = config.urlEnv
    ? `os.environ[${JSON.stringify(config.urlEnv)}]`
    : JSON.stringify(config.url);
  const lines: string[] = [
    `        "driver": ${JSON.stringify(config.driver)},`,
    `        "url": ${url},`,
  ];
  if (config.maxConnections !== undefined)
    lines.push(`        "max_connections": ${config.maxConnections},`);
  if (config.stripTimezone !== undefined)
    lines.push(`        "strip_timezone": ${pyBool(config.stripTimezone)},`);
  if (config.cache) {
    const parts = [`"enabled": ${pyBool(config.cache.enabled)}`];
    if (config.cache.walPath !== undefined)
      parts.push(`"wal_path": ${JSON.stringify(config.cache.walPath)}`);
    if (config.cache.compactionThreshold !== undefined)
      parts.push(`"compaction_threshold": ${config.cache.compactionThreshold}`);
    lines.push(`        "cache": {${parts.join(", ")}},`);
  }
  return lines.join("\n");
}

/** Python module name for `from <module> import schema` (stem of the schema file). */
function pyModuleName(schemaFsPath: string): string {
  const base = schemaFsPath.replace(/\\/g, "/").split("/").pop() ?? "schema";
  return base.replace(/\.py$/, "");
}

function renderClientPy(config: AgnesConfig, schemaModule: string): string {
  const importOs = config.urlEnv ? "import os\n" : "";
  return (
    `# Generated by \`agnes generate\`. Do not edit — re-run to regenerate.\n` +
    `${importOs}from agnes import AgnesClient\n` +
    `from ${schemaModule} import schema\n\n` +
    `db = AgnesClient.create(\n` +
    `    {\n${renderConfigObjectPy(config)}\n    },\n` +
    `    schema,\n` +
    `)\n`
  );
}

/** Emit a ready-to-import AgnesClient module wired to the config. */
export async function generate(config: AgnesConfig, args: GenerateArgs): Promise<void> {
  const outRel = args.output ?? config.output;
  if (!outRel) {
    throw new Error(
      `No output path. Set \`output\` in agnes.config.ts (e.g. "src/services/db.ts") or pass --output <path>.`,
    );
  }

  const isPy = outRel.endsWith(".py");
  const outPath = resolve(process.cwd(), outRel);
  const defaultSchema = isPy ? "schema.py" : "schema.ts";
  const schemaFsPath = resolve(process.cwd(), config.schemaPath ?? config.out ?? defaultSchema);
  const schemaImport = isPy ? pyModuleName(schemaFsPath) : toImportSpecifier(outPath, schemaFsPath);

  if (!config.urlEnv) {
    console.log(
      c.yellow(
        `⚠ config.urlEnv is not set — the connection URL will be INLINED into ${outRel}.`,
      ),
    );
    console.log(c.dim(`  Set urlEnv (e.g. "DATABASE_URL") to read it from the environment instead.`));
  }

  const source = isPy
    ? renderClientPy(config, schemaImport)
    : renderClient(config, schemaImport);

  if (await Bun.file(outPath).exists() && !args.yes) {
    console.log(c.yellow(`⚠ ${outPath} already exists and will be overwritten.`));
    const { confirm } = await import("../prompt");
    if (!(await confirm("Overwrite it?"))) {
      console.log(c.dim("Aborted. File left unchanged."));
      return;
    }
  }

  await Bun.write(outPath, source);
  console.log(c.green(`✓ Generated client → ${outPath}`));
  console.log(c.dim(`  imports schema from ${schemaImport}`));
}
