import { dirname, relative, resolve } from "node:path";
import type { AgnesConfig } from "../config";
import { c } from "../prompt";

export interface GenerateArgs {
  output?: string;
  yes?: boolean;
}

/** Turn a filesystem path into a relative ESM import specifier (no extension). */
function toImportSpecifier(fromFile: string, toModule: string): string {
  let rel = relative(dirname(fromFile), toModule).replace(/\\/g, "/");
  rel = rel.replace(/\.(ts|tsx|js|jsx|mjs|cjs)$/, "");
  if (!rel.startsWith(".")) rel = `./${rel}`;
  return rel;
}

function renderConfigObject(config: AgnesConfig): string {
  const lines: string[] = [
    `    driver: ${JSON.stringify(config.driver)},`,
    `    url: ${JSON.stringify(config.url)},`,
  ];
  if (config.maxConnections !== undefined)
    lines.push(`    maxConnections: ${config.maxConnections},`);
  if (config.cache) {
    const parts = [`enabled: ${config.cache.enabled}`];
    if (config.cache.walPath !== undefined) parts.push(`walPath: ${JSON.stringify(config.cache.walPath)}`);
    if (config.cache.compactionThreshold !== undefined)
      parts.push(`compactionThreshold: ${config.cache.compactionThreshold}`);
    lines.push(`    cache: { ${parts.join(", ")} },`);
  }
  return lines.join("\n");
}

function renderClient(config: AgnesConfig, schemaImport: string): string {
  return (
    `// Generated by \`agnes generate\`. Do not edit — re-run to regenerate.\n` +
    `import { AgnesClient } from "agnes-library";\n` +
    `import { schema } from ${JSON.stringify(schemaImport)};\n\n` +
    `export const db = await AgnesClient.create(\n` +
    `  {\n${renderConfigObject(config)}\n  },\n` +
    `  schema,\n` +
    `);\n`
  );
}

/** Emit a ready-to-import AgnesClient module wired to the config. */
export async function generate(config: AgnesConfig, args: GenerateArgs): Promise<void> {
  const outRel = args.output ?? config.output;
  if (!outRel) {
    throw new Error(
      `No output path. Set \`output\` in agnes.config.ts (e.g. "src/services/db.ts") or pass --output <path>.`,
    );
  }

  const outPath = resolve(process.cwd(), outRel);
  const schemaFsPath = resolve(process.cwd(), config.schemaPath ?? config.out ?? "schema.ts");
  const schemaImport = toImportSpecifier(outPath, schemaFsPath);

  const source = renderClient(config, schemaImport);

  if (await Bun.file(outPath).exists() && !args.yes) {
    console.log(c.yellow(`⚠ ${outPath} already exists and will be overwritten.`));
    const { confirm } = await import("../prompt");
    if (!(await confirm("Overwrite it?"))) {
      console.log(c.dim("Aborted. File left unchanged."));
      return;
    }
  }

  await Bun.write(outPath, source);
  console.log(c.green(`✓ Generated client → ${outPath}`));
  console.log(c.dim(`  imports schema from ${schemaImport}`));
}
