import { resolve } from "node:path";
import { readdir } from "node:fs/promises";
import type { AgnesConfig } from "../config";
import type { Dialect } from "../dialect";
import { openDb, type CliDb } from "../db";
import { diffSchemas } from "../diff";
import { renderPlan } from "../generate";
import { schemaToIR } from "../ir";
import { normalizeIR } from "../normalize";
import { introspect } from "../introspect";
import { c, confirm } from "../prompt";

export interface MigrateArgs {
  yes?: boolean;
  dryRun?: boolean;
  dir?: string;
  name?: string;
}

const DESTRUCTIVE = /\bDROP\s+(TABLE|COLUMN|CONSTRAINT|FOREIGN\s+KEY)\b/i;

function trackingTableDdl(dialect: Dialect): string {
  const nameType = dialect === "mysql" ? "VARCHAR(255)" : "TEXT";
  return (
    `CREATE TABLE IF NOT EXISTS _agnes_migrations (` +
    `name ${nameType} PRIMARY KEY, ` +
    `applied_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP)`
  );
}

function timestamp(): string {
  const d = new Date();
  const p = (n: number, w = 2) => String(n).padStart(w, "0");
  return (
    `${d.getFullYear()}${p(d.getMonth() + 1)}${p(d.getDate())}` +
    `${p(d.getHours())}${p(d.getMinutes())}${p(d.getSeconds())}`
  );
}

function splitStatements(sql: string): string[] {
  return sql
    .split(";")
    // Strip full-line SQL comments so a leading `-- header` doesn't swallow the
    // statement that follows it on the next line.
    .map((chunk) =>
      chunk
        .split("\n")
        .filter((line) => !line.trim().startsWith("--"))
        .join("\n")
        .trim(),
    )
    .filter((s) => s.length > 0);
}

/** Generate a new migration from schema drift, then apply all pending files. */
export async function migrate(config: AgnesConfig, args: MigrateArgs): Promise<void> {
  console.log(c.cyan(`agnes migrate → ${config.driver}`));
  const db = await openDb(config);
  const dir = resolve(process.cwd(), args.dir ?? config.migrationsDir ?? "migrations");

  await db.mutate(trackingTableDdl(config.driver));

  // 1. Detect drift and write a new migration file.
  const desired = normalizeIR(schemaToIR(config.schema), config.driver);
  const current = normalizeIR(await introspect(db, config.driver), config.driver);
  const ops = diffSchemas(desired, current);

  if (ops.length > 0) {
    const statements = renderPlan(config.driver, ops);
    const fileName = `${timestamp()}_${args.name ?? "auto"}.sql`;
    const filePath = resolve(dir, fileName);
    const body = statements.map((s) => (s.startsWith("--") ? s : `${s}`)).join("\n\n") + "\n";

    if (args.dryRun) {
      console.log(c.bold(`\nWould create ${fileName}:`));
      console.log(c.dim(body));
    } else {
      await Bun.write(filePath, `-- Migration ${fileName}\n-- Generated by \`agnes migrate\`\n\n${body}`);
      console.log(c.green(`✓ Created migration ${fileName} (${statements.length} statement(s))`));
    }
  } else {
    console.log(c.dim("No schema drift — no new migration generated."));
  }

  // 2. Apply pending migration files.
  await applyPending(db, config.driver, dir, args);
}

async function applyPending(
  db: CliDb,
  dialect: Dialect,
  dir: string,
  args: MigrateArgs,
): Promise<void> {
  let files: string[];
  try {
    files = (await readdir(dir)).filter((f) => f.endsWith(".sql")).sort();
  } catch {
    files = [];
  }

  const appliedRows = await db.query<{ name: string }>(`SELECT name FROM _agnes_migrations`);
  const applied = new Set(appliedRows.map((r) => String(r.name)));
  const pending = files.filter((f) => !applied.has(f));

  if (pending.length === 0) {
    console.log(c.green("\n✓ No pending migrations."));
    return;
  }

  console.log(c.bold(`\nPending migrations (${pending.length}):`));
  for (const f of pending) console.log("  " + c.green(f));

  if (args.dryRun) {
    console.log(c.dim("\nDry run — not applied."));
    return;
  }

  // Confirm if any pending file contains destructive statements.
  const bodies = new Map<string, string>();
  let anyDestructive = false;
  for (const f of pending) {
    const text = await Bun.file(resolve(dir, f)).text();
    bodies.set(f, text);
    if (DESTRUCTIVE.test(text)) anyDestructive = true;
  }

  if (anyDestructive && !args.yes) {
    console.log(c.yellow("\n⚠ Some pending migrations contain destructive statements (DROP)."));
    const ok = await confirm("Apply all pending migrations?");
    if (!ok) {
      console.log(c.dim("Aborted. No migrations applied."));
      return;
    }
  }

  for (const f of pending) {
    console.log(c.bold(`\nApplying ${f}...`));
    for (const stmt of splitStatements(bodies.get(f)!)) {
      await db.mutate(stmt);
      console.log(c.dim("  ✓ " + stmt.split("\n")[0]));
    }
    await db.mutate(`INSERT INTO _agnes_migrations (name) VALUES (${dialect === "postgres" ? "$1" : "?"})`, [f]);
  }
  console.log(c.green(`\n✓ Applied ${pending.length} migration(s).`));
}
