/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class Database {
  static connect(config: DatabaseConfig): Promise<Database>
  query(sql: string, params?: Array<any> | undefined | null, opts?: QueryOpts | undefined | null): Promise<any>
  mutate(sql: string, params?: Array<any> | undefined | null): Promise<number>
}

export interface CacheConfig {
  enabled: boolean
  walPath?: string
  compactionThreshold?: number
}

export interface DatabaseConfig {
  driver: string
  url: string
  maxConnections?: number
  cache?: CacheConfig
  /**
   * Return temporal values without a timezone offset (naive wall-clock ISO).
   * Avoids the JS `Date` tz-shift footgun. Postgres only; defaults to false.
   */
  stripTimezone?: boolean
}

export interface QueryOpts {
  ttl?: number
  cacheKey?: string
  bypassCache?: boolean
}
