/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class Database {
  static connect(config: DatabaseConfig): Promise<Database>
  query(sql: string, params?: Array<any> | undefined | null, opts?: QueryOpts | undefined | null): Promise<any>
  mutate(sql: string, params?: Array<any> | undefined | null): Promise<number>
  /**
   * Stream a read query row-by-row (constant memory). Pull batches from the
   * returned handle with `nextBatch(n)`; an empty batch means end of stream.
   */
  stream(sql: string, params?: Array<any> | undefined | null): Promise<RowStream>
  /** Open an interactive transaction on a dedicated connection. */
  beginTransaction(): Promise<Transaction>
}

/**
 * A pull-based row stream. `nextBatch(n)` resolves to up to `n` rows; an empty
 * array means the stream is exhausted.
 */
export declare class RowStream {
  nextBatch(n: number): Promise<any>
}

/**
 * A live transaction handle. `query`/`mutate` run on the transaction's
 * connection; `commit`/`rollback` finish it (further calls error).
 */
export declare class Transaction {
  query(sql: string, params?: Array<any> | undefined | null, opts?: QueryOpts | undefined | null): Promise<any>
  mutate(sql: string, params?: Array<any> | undefined | null): Promise<number>
  commit(): Promise<void>
  rollback(): Promise<void>
}

export interface CacheConfig {
  enabled: boolean
  walPath?: string
  compactionThreshold?: number
}

export interface DatabaseConfig {
  driver: string
  url: string
  /** Max open connections in the pool (default 10). */
  maxConnections?: number
  /** Connections kept warm even while idle (default 0). */
  minConnections?: number
  /** Seconds `acquire` waits for a free connection before erroring. */
  acquireTimeoutSecs?: number
  /** Close a connection after it has been idle this many seconds. */
  idleTimeoutSecs?: number
  /** Recycle a connection after it has lived this many seconds. */
  maxLifetimeSecs?: number
  cache?: CacheConfig
  /**
   * Return temporal values without a timezone offset (naive wall-clock ISO).
   * Avoids the JS `Date` tz-shift footgun. Postgres only; defaults to false.
   */
  stripTimezone?: boolean
}

export interface QueryOpts {
  ttl?: number
  cacheKey?: string
  bypassCache?: boolean
}
