// Generated by `agnes generate`. Do not edit — re-run to regenerate.
import { AgnesClient } from "agnes-library";
import { schema } from "./schema";

export const db = await AgnesClient.create(
  {
    driver: "sqlite",
    url: "sqlite:./demo.db",
    cache: { enabled: true, walPath: ".agnes/cache.wal" },
  },
  schema,
);
